# Generated by Django 4.2.7 on 2025-06-24 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
