# Generated by Django 4.1.13 on 2025-06-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyProfileAdmin',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='student',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='faculty',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.faculty'),
            preserve_default=False,
        ),
    ]
