# Generated by Django 5.2.1 on 2025-05-25 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college_name', models.CharField(choices=[('CCS', 'CCS'), ('CASE', 'CASE')], max_length=10)),
                ('department_name', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('Arts', 'Arts'), ('Science', 'Science'), ('Education', 'Education')], max_length=20)),
                ('status', models.CharField(choices=[('Fulltime', 'Fulltime'), ('Parttime', 'Parttime')], max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course_and_year',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrolled_class',
        ),
        migrations.AddField(
            model_name='class',
            name='class_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='class',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_classes',
            field=models.ManyToManyField(related_name='students', through='core.Enrollment', to='core.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity_type', models.CharField(choices=[('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('Seatwork', 'Seatwork'), ('Laboratory', 'Laboratory'), ('Prelim', 'Prelim'), ('Midterm', 'Midterm'), ('Pre-Final', 'Pre-Final'), ('Final', 'Final')], max_length=20)),
                ('activity_name', models.CharField(max_length=100)),
                ('score', models.FloatField(blank=True, null=True)),
                ('perfect_score', models.FloatField(default=100)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='core.enrollment')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculty')),
            ],
            options={
                'unique_together': {('enrollment', 'activity_type', 'activity_name')},
            },
        ),
    ]
