# Generated by Django 4.1.13 on 2025-07-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_quiz_quizattempt_quizchoice_quizquestion_and_more'),
        ('core', '0002_course_seatworkrecord_conversation_muted_by_and_more'),
    ]

    operations = [
    ]
