# Generated by Django 5.2.1 on 2025-06-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='published_date',
            new_name='created_at',
        ),
    ]
