# Generated by Django 4.1.13 on 2025-07-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250705_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_classes', to='core.faculty'),
        ),
    ]
