# Generated by Django 4.2 on 2025-07-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgrade',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
