# Generated by Django 4.1.13 on 2025-06-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_class_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
