# Generated by Django 4.1.13 on 2025-06-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_facultyprofileadmin_delete_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
