# Generated by Django 4.1.13 on 2025-06-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enrollment_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_archived',
        ),
        migrations.CreateModel(
            name='FavoriteClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'unique_together': {('student', 'class_obj')},
            },
        ),
    ]
