# Generated by Django 4.1.13 on 2025-07-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20250701_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='course',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='muted_by',
        ),
        migrations.DeleteModel(
            name='FavoriteCourse',
        ),
    ]
