# Generated by Django 5.2.3 on 2025-07-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_conversation_muted_by_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='course',
            new_name='class_obj',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='course',
            new_name='class_obj',
        ),
    ]
