# Generated by Django 4.1.13 on 2025-06-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enrollment_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faculty'),
        ),
    ]
