# Generated by Django 4.1.13 on 2025-07-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_class_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='muted_by',
            field=models.ManyToManyField(blank=True, related_name='muted_conversations', to='core.student'),
        ),
    ]
