# Generated by Django 5.2.1 on 2025-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
