# Generated by Django 4.2.21 on 2025-06-16 06:38

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(
                choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')],
                default='ACTIVE',
                max_length=10
            ),
          field=models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=10), 
        ),
    ]
