# Generated by Django 5.2.3 on 2025-07-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_course_activity_class_obj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
