# Generated by Django 5.2.1 on 2025-05-26 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'enrolled_class')},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faculty'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('faculty', 'enrolled_class'), ('student', 'enrolled_class')},
        ),
    ]
