# Generated by Django 5.1.2 on 2025-07-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_grade_activity_remove_grade_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
