# Generated by Django 5.1.2 on 2025-07-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attendance_feedback'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'class_obj', 'date'), name='unique_student_class_date_attendance'),
        ),
    ]
