# Generated by Django 5.2.1 on 2025-05-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='core.student'),
        ),
    ]
