# Generated by Django 4.2.21 on 2025-06-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activityrecord_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
