# Generated by Django 4.2.21 on 2025-06-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_faculty_is_disabled_student_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DISABLED', 'DISABLED')], default='ACTIVE', max_length=10),
        ),
    ]
