# Generated by Django 4.2 on 2025-06-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='profile_picture',
        ),
    ]
