# Generated by Django 4.2 on 2025-06-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfileAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='FacultyProfile',
        ),
    ]
