# Generated by Django 4.2 on 2025-06-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to='student_profiles'),
        ),
    ]
