# Generated by Django 4.2 on 2025-06-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_auto_20250618_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='avatar',
            field=models.CharField(default='default_avatar.jpg', max_length=255),
        ),
    ]
