# Generated by Django 4.2 on 2025-06-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0003_alter_studentprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles'),
        ),
    ]
