# Generated by Django 5.2.4 on 2025-07-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit_student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
