# Generated by Django 4.2.21 on 2025-07-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit_student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
